#!/usr/bin/env bash

sudo apt install -y tcpdump
X=$(hostname)
sudo ip addr add 172.20.15.${X: -1}/32 dev lo
case $(hostname) in
    R1)
        sudo ip route add 172.20.15.3/32 encap mpls 100 via inet 192.168.12.102
        ;;
    R2)
        sudo modprobe mpls_router
        sudo sysctl net.mpls.conf.ens6.input=1
        sudo sysctl net.mpls.conf.ens7.input=1
        sudo sysctl net.mpls.platform_labels=2048
        sudo ip -M route add 100 via inet 192.168.23.101
        sudo ip -M route add 200 via inet 192.168.12.101
        ;;
    R3)
        sudo ip route add 172.20.15.1/32 encap mpls 200 via inet 192.168.23.102
        ;;
    *)
        echo "unknown hostname $(hostname)"
        ;;
esac
