Vagrant.configure("2") do |config|
  config.vm.define "r1" do |r1|
      r1.vm.box = "debian/buster64"
      r1.vm.hostname = "R1"
      r1.vm.network "private_network", ip: "192.168.12.101", libvirt_network_name: "nix12", libvirt_iface_name: "eth1"
      r1.vm.provision "shell", path: "frr_provisioning"
  end
  config.vm.define "r2" do |r2|
      r2.vm.box = "debian/buster64"
      r2.vm.hostname = "R2"
      r2.vm.network "private_network", ip: "192.168.12.102", libvirt_network_name: "nix12", libvirt_iface_name: "eth1"
      r2.vm.network "private_network", ip: "192.168.23.102", libvirt_network_name: "nix23", libvirt_iface_name: "eth2"
      r2.vm.provision "shell", path: "frr_provisioning"
  end
  config.vm.define "r3" do |r3|
      r3.vm.box = "debian/buster64"
      r3.vm.hostname = "R3"
      r3.vm.network "private_network", ip: "192.168.23.101", libvirt_network_name: "nix23", libvirt_iface_name: "eth2"
      r3.vm.provision "shell", path: "frr_provisioning"
  end
end
